
package com.prechtl.bank;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TransactionServiceIF", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransactionServiceIF {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.prechtl.bank.TransactionDTO
     * @throws LoginException_Exception
     * @throws TransactionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "directDebit", targetNamespace = "http://service/", className = "com.prechtl.bank.DirectDebit")
    @ResponseWrapper(localName = "directDebitResponse", targetNamespace = "http://service/", className = "com.prechtl.bank.DirectDebitResponse")
    public TransactionDTO directDebit(
        @WebParam(name = "arg0", targetNamespace = "")
        LoginDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        TransactionDTO arg1)
        throws LoginException_Exception, TransactionException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.prechtl.bank.TransactionDTO
     * @throws LoginException_Exception
     * @throws TransactionException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transfer", targetNamespace = "http://service/", className = "com.prechtl.bank.Transfer")
    @ResponseWrapper(localName = "transferResponse", targetNamespace = "http://service/", className = "com.prechtl.bank.TransferResponse")
    public TransactionDTO transfer(
        @WebParam(name = "arg0", targetNamespace = "")
        LoginDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        TransactionDTO arg1)
        throws LoginException_Exception, TransactionException_Exception
    ;

}
