
package com.prechtl.bank;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "LoginException", targetNamespace = "http://service/")
public class LoginException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private LoginException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public LoginException_Exception(String message, LoginException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public LoginException_Exception(String message, LoginException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.prechtl.bank.LoginException
     */
    public LoginException getFaultInfo() {
        return faultInfo;
    }

}
